title: "LifeOnFloor"
description: "one sheep, two sheep, three..."
baseurl: "/blog"
url: "https://LifeOnFloor.github.io"

remote_theme: "mmistakes/minimal-mistakes@4.26.2"

plugins:
  - jekyll-optional-front-matter
  - jekyll-include-cache

# Build settings
markdown: kramdown
highlighter: rouge

minimal_mistakes_skin: "dark"
